# Generated by Django 5.0.8 on 2024-08-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='users',
            name='fullName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
