# Generated by Django 5.0.8 on 2024-08-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_birthday_users_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fullName',
            field=models.CharField(max_length=255),
        ),
    ]
